/**
 * Main-thread facade for the PDF worker. Each call posts to a single shared worker and resolves
 * with its result. Inputs are copied (the UI keeps its originals for previews); outputs are transferred.
 */
import type * as Ops from './ops';

type Fn<K extends keyof typeof Ops> = (typeof Ops)[K] extends (...a: infer A) => infer R ? (...a: A) => Promise<Awaited<R>> : never;

let worker: Worker | null = null;
let seq = 0;
const pending = new Map<number, { resolve: (v: unknown) => void; reject: (e: Error) => void }>();

function getWorker(): Worker {
  if (!worker) {
    worker = new Worker(new URL('../../workers/pdf.worker.ts', import.meta.url), { type: 'module', name: 'pdf-ops' });
    worker.onmessage = (e: MessageEvent<{ id: number; result?: unknown; error?: string }>) => {
      const p = pending.get(e.data.id);
      if (!p) return;
      pending.delete(e.data.id);
      if (e.data.error !== undefined) p.reject(new Error(e.data.error));
      else p.resolve(e.data.result);
    };
    worker.onerror = (e) => {
      // A crashed worker (e.g. out of memory) rejects everything in flight; the next call starts a fresh one.
      pending.forEach((p) => p.reject(new Error(e.message || 'The PDF engine stopped unexpectedly (the file may be too large)')));
      pending.clear();
      worker?.terminate();
      worker = null;
    };
  }
  return worker;
}

function call<K extends keyof typeof Ops>(op: K): Fn<K> {
  return ((...args: unknown[]) =>
    new Promise((resolve, reject) => {
      const id = ++seq;
      pending.set(id, { resolve, reject });
      getWorker().postMessage({ id, op, args });
    })) as Fn<K>;
}

export const pdfOps = {
  organize: call('organize'),
  merge: call('merge'),
  split: call('split'),
  insertPages: call('insertPages'),
  imagesToPdf: call('imagesToPdf'),
  watermark: call('watermark'),
  addPageNumbers: call('addPageNumbers'),
  readMeta: call('readMeta'),
  writeMeta: call('writeMeta'),
  zipFiles: call('zipFiles'),
  makeSample: call('makeSample'),
  clean: call('clean'),
};

/** Wraps generated bytes as a File so tools can treat samples like uploads. */
export async function sampleFile(pages = 6, name = 'sample-loan-file.pdf'): Promise<File> {
  const bytes = await pdfOps.makeSample(pages);
  return new File([bytes as BlobPart], name, { type: 'application/pdf' });
}
