import { useEffect, useState } from 'react';
import { Check, Copy, Download, KeyRound, RefreshCw } from 'lucide-react';
import ToolShell from '../../components/tool/ToolShell';
import ErrorBox from '../../components/tool/ErrorBox';
import Loader from '../../components/ui/Loader';
import Tabs from '../../components/ui/Tabs';
import { useAction } from '../../components/tool/useAction';
import { Checkbox, Segmented, Select, TextArea } from '../../components/ui/controls';
import {
  generateKeyPair,
  generatePassword,
  passwordEntropyBits,
  randomSecret,
  uuid,
  type GeneratedKeyPair,
  type KeyPairType,
  type PasswordOptions,
  type SecretFormat,
} from '../../lib/crypto/keys';
import { copyText, downloadBlob } from '../../lib/files';

type Tab = 'keypair' | 'password' | 'secret' | 'uuid';

function CopyBtn({ text, label }: { text: string; label: string }) {
  const [done, setDone] = useState(false);
  return (
    <button
      type="button"
      className="hud-btn hud-btn-ghost px-2 py-1 text-xs"
      disabled={!text}
      aria-label={`Copy ${label}`}
      onClick={async () => {
        if (await copyText(text)) {
          setDone(true);
          setTimeout(() => setDone(false), 1000);
        }
      }}
    >
      {done ? <Check size={14} className="text-success" /> : <Copy size={14} />} {done ? 'Copied' : 'Copy'}
    </button>
  );
}

function KeyPairPanel() {
  const [type, setType] = useState<KeyPairType>('RSA-2048');
  const [format, setFormat] = useState<'pem' | 'jwk'>('pem');
  const [pair, setPair] = useState<GeneratedKeyPair | null>(null);
  const { error, run, busy } = useAction();
  const pub = pair ? (format === 'pem' ? pair.publicPem : pair.publicJwk) : '';
  const priv = pair ? (format === 'pem' ? pair.privatePem : pair.privateJwk) : '';
  return (
    <div className="space-y-3 p-4">
      <div className="flex flex-wrap items-end gap-4">
        <Segmented
          label="Type"
          value={type}
          onChange={setType}
          options={[
            { value: 'RSA-2048', label: 'RSA 2048' },
            { value: 'RSA-4096', label: 'RSA 4096' },
            { value: 'EC-P256', label: 'EC P-256' },
            { value: 'EC-P384', label: 'EC P-384' },
          ]}
        />
        <Segmented
          label="Format"
          value={format}
          onChange={setFormat}
          options={[
            { value: 'pem', label: 'PEM' },
            { value: 'jwk', label: 'JWK' },
          ]}
        />
        <button type="button" className="hud-btn hud-btn-accent" disabled={busy} onClick={() => run(async () => setPair(await generateKeyPair(type)))}>
          {busy ? <Loader /> : <KeyRound size={15} aria-hidden="true" />} Generate key pair
        </button>
        {busy && type === 'RSA-4096' && <span className="text-xs text-muted">RSA-4096 can take a few seconds…</span>}
      </div>
      {error && <ErrorBox error={error} className="rounded border" />}
      {pair && (
        <div className="grid gap-4 lg:grid-cols-2">
          {[
            ['Public key', pub, format === 'pem' ? 'public.pem' : 'public.jwk.json'],
            ['Private key — keep secret', priv, format === 'pem' ? 'private.pem' : 'private.jwk.json'],
          ].map(([label, value, file]) => (
            <div key={label}>
              <div className="mb-1 flex items-center gap-1">
                <span className="hud-label mb-0 flex-1">{label}</span>
                <CopyBtn text={value} label={label} />
                <button type="button" className="hud-btn hud-btn-ghost px-2 py-1 text-xs" onClick={() => downloadBlob(value, file)}>
                  <Download size={14} aria-hidden="true" /> Save
                </button>
              </div>
              <textarea readOnly value={value} rows={12} className="hud-input resize-y font-mono text-xs" aria-label={label} />
            </div>
          ))}
        </div>
      )}
      <p className="text-xs text-muted">Keys are generated by your browser’s Web Crypto API and exist only on this page. Clear them when you are done.</p>
    </div>
  );
}

function PasswordPanel() {
  const [o, setO] = useState<PasswordOptions>({ length: 20, lower: true, upper: true, digits: true, symbols: true, excludeAmbiguous: true });
  const [count, setCount] = useState('5');
  const [list, setList] = useState<string[]>([]);
  const [err, setErr] = useState('');
  const regen = () => {
    try {
      setList(Array.from({ length: +count }, () => generatePassword(o)));
      setErr('');
    } catch (e) {
      setErr((e as Error).message);
      setList([]);
    }
  };
  useEffect(regen, [o, count]);
  const bits = passwordEntropyBits(o);
  return (
    <div className="space-y-3 p-4">
      <div className="flex flex-wrap items-end gap-4">
        <label className="flex flex-col">
          <span className="hud-label">Length: {o.length}</span>
          <input
            type="range"
            min={8}
            max={64}
            value={o.length}
            onChange={(e) => setO({ ...o, length: +e.target.value })}
            className="w-48 accent-[rgb(var(--accent))]"
          />
        </label>
        <div className="grid grid-cols-2 gap-x-4 gap-y-1">
          <Checkbox label="a–z" checked={o.lower} onChange={(v) => setO({ ...o, lower: v })} />
          <Checkbox label="A–Z" checked={o.upper} onChange={(v) => setO({ ...o, upper: v })} />
          <Checkbox label="0–9" checked={o.digits} onChange={(v) => setO({ ...o, digits: v })} />
          <Checkbox label="Symbols" checked={o.symbols} onChange={(v) => setO({ ...o, symbols: v })} />
        </div>
        <Checkbox label="Exclude look-alikes (O 0 l 1 I |)" checked={o.excludeAmbiguous} onChange={(v) => setO({ ...o, excludeAmbiguous: v })} />
        <Select label="How many" value={count} onChange={setCount} options={['1', '5', '10', '20']} />
        <button type="button" className="hud-btn hud-btn-accent" onClick={regen}>
          <RefreshCw size={15} aria-hidden="true" /> Regenerate
        </button>
      </div>
      <p className={`text-sm ${bits >= 80 ? 'text-success' : bits >= 60 ? 'text-warn' : 'text-danger'}`}>
        Strength ≈ {bits} bits of entropy {bits >= 80 ? '(strong)' : bits >= 60 ? '(fair)' : '(weak)'}
      </p>
      {err && (
        <p role="alert" className="text-sm text-danger">
          {err}
        </p>
      )}
      <ul className="space-y-1.5">
        {list.map((p, i) => (
          <li key={i} className="flex items-center gap-2 rounded border border-primary/30 bg-[var(--surface-strong)] px-3 py-1.5">
            <code className="flex-1 break-all font-mono text-sm">{p}</code>
            <CopyBtn text={p} label="password" />
          </li>
        ))}
      </ul>
    </div>
  );
}

function SecretPanel() {
  const [bytes, setBytes] = useState('32');
  const [format, setFormat] = useState<SecretFormat>('base64url');
  const [value, setValue] = useState('');
  useEffect(() => setValue(randomSecret(+bytes, format)), [bytes, format]);
  return (
    <div className="space-y-3 p-4">
      <div className="flex flex-wrap items-end gap-4">
        <Select
          label="Length"
          value={bytes}
          onChange={setBytes}
          options={[
            { value: '16', label: '16 bytes (128-bit)' },
            { value: '32', label: '32 bytes (256-bit)' },
            { value: '64', label: '64 bytes (512-bit)' },
          ]}
        />
        <Segmented
          label="Encoding"
          value={format}
          onChange={setFormat}
          options={[
            { value: 'hex', label: 'Hex' },
            { value: 'base64', label: 'Base64' },
            { value: 'base64url', label: 'Base64URL' },
          ]}
        />
        <button type="button" className="hud-btn hud-btn-accent" onClick={() => setValue(randomSecret(+bytes, format))}>
          <RefreshCw size={15} aria-hidden="true" /> Regenerate
        </button>
        <CopyBtn text={value} label="secret" />
      </div>
      <TextArea label="Random secret (e.g. HMAC key, JWT HS256 secret, API key)" value={value} readOnly rows={3} />
    </div>
  );
}

function UuidPanel() {
  const [version, setVersion] = useState<'4' | '7'>('4');
  const [count, setCount] = useState('10');
  const [upper, setUpper] = useState(false);
  const [list, setList] = useState('');
  const regen = () => {
    const ids = Array.from({ length: +count }, () => uuid(+version as 4 | 7));
    setList((upper ? ids.map((u) => u.toUpperCase()) : ids).join('\n'));
  };
  useEffect(regen, [version, count, upper]);
  return (
    <div className="space-y-3 p-4">
      <div className="flex flex-wrap items-end gap-4">
        <Segmented
          label="Version"
          value={version}
          onChange={setVersion}
          options={[
            { value: '4', label: 'v4 (random)' },
            { value: '7', label: 'v7 (time-ordered)' },
          ]}
        />
        <Select label="How many" value={count} onChange={setCount} options={['1', '10', '50', '100', '1000']} />
        <div className="pb-2">
          <Checkbox label="Upper case" checked={upper} onChange={setUpper} />
        </div>
        <button type="button" className="hud-btn hud-btn-accent" onClick={regen}>
          <RefreshCw size={15} aria-hidden="true" /> Regenerate
        </button>
        <CopyBtn text={list} label="UUIDs" />
      </div>
      <textarea readOnly value={list} rows={12} className="hud-input font-mono text-xs" aria-label="UUIDs" />
      <p className="text-xs text-muted">v7 UUIDs sort by creation time, which keeps database indexes compact.</p>
    </div>
  );
}

export default function KeygenTool() {
  const [tab, setTab] = useState<Tab>('keypair');
  const [nonce, setNonce] = useState(0);
  return (
    <ToolShell onClear={() => setNonce((n) => n + 1)}>
      <section className="hud-panel">
        <Tabs
          value={tab}
          onChange={setTab}
          tabs={[
            { id: 'keypair', label: 'Key pair' },
            { id: 'password', label: 'Password' },
            { id: 'secret', label: 'Random secret' },
            { id: 'uuid', label: 'UUID' },
          ]}
        >
          <div key={`${tab}-${nonce}`}>
            {tab === 'keypair' && <KeyPairPanel />}
            {tab === 'password' && <PasswordPanel />}
            {tab === 'secret' && <SecretPanel />}
            {tab === 'uuid' && <UuidPanel />}
          </div>
        </Tabs>
      </section>
    </ToolShell>
  );
}
